# Generated by Django 4.1.2 on 2022-11-07 02:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='consulta',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
