# Generated by Django 4.1 on 2022-11-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_reserva_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
